### ISSUE TITLE
v2.0 calculations always result in Will kill: false

### ISSUE THREAD

**Issue by mike406** [Vhou-Atroph/TT-Damage-Calculator#15]
Unless I am doing something wrong, it seems that no matter what gags I pick using a v2.0 calculation does not report if the Cog will be defeated. This should be modified to show if the outer "shell" of the v2.0 Cog will be defeated by the selected gags. Older versions when v2.0 was a checkbox worked as expected, so this may be a regression.

**Comment by Vhou-Atroph** [comment]
I believe this is fixed now, please let me know if the problem persists!
