### ISSUE TITLE
[Enhancement] Live Calculation and Cog HP Comparison

### ISSUE THREAD

**Issue by supdogpsi** [Vhou-Atroph/TT-Damage-Calculator#3]
This program is a interesting little starting point, but I think it needs two major features to help it truly shine.

Live Calculation - Calculate damage on-the-fly, rather then requiring the "calculate" button. This is a huge timesaver, as you could simply click a gag until you have enough to defeat a cog, or rapidly find combinations on-the-fly. 

Cog HP Comparison - While the "Show Health" table is nice, I think it's possible (if not easy) to automatically calculate the max level cog the calculated result can kill. Example: 198 damage (Kills up to Level 12)

**Comment by Vhou-Atroph** [comment]
> Cog HP Comparison - While the "Show Health" table is nice, I think it's possible (if not easy) to automatically calculate the max level cog the calculated result can kill. Example: 198 damage (Kills up to Level 12)

I will look into implementing this next.

> Live Calculation - Calculate damage on-the-fly, rather then requiring the "calculate" button. This is a huge timesaver, as you could simply click a gag until you have enough to defeat a cog, or rapidly find combinations on-the-fly.

I decided to make a demo for this and it works well. The only issue is I don't know if I want it to be on this project, or a separate calculator with specifically endgame play in mind. Either way, I'll make this happen and am curious about your and others' preferences regarding this.

**Comment by Vhou-Atroph** [comment]
A commit for Cog HP Comparison has been pushed.
![coghealthind](https://user-images.githubusercontent.com/79807240/145723656-4f793bfb-3172-4cde-8c8b-7b0b3f84002b.png)

**Comment by supdogpsi** [comment]
Wonderful, thanks!
On the topic of live calculation, I personally don't see a need to make it a separate program (it's solely a useful time-saving feature that streamlines the utility), but it is your program, so it's your choice. (it might be a bit more difficult to maintain both, though, and I see live calculation as solely superior)
When tinkering with the live version, the only thing that could be a _tiny_ bit awkward is having to use clear inputs because you can use more then 4 gags in one turn - I initially was using clear history only to find it kept adding damage.

While this is a semi-unrelated suggestion, perhaps history could be supplemented/replaced by small number indicators next to gags (showing 3 if you clicked on 3 hoses, for example.), just to add a extra level of user-friendliness.

**Comment by Vhou-Atroph** [comment]
Got it- the plan is to have one program, then.  
Thank you for the feedback on the live version, I'll look into making it clearer what the button does, and if you have any suggestions on how to do that I'd be very glad to hear them. It can be very difficult to see issues in things when I've been looking at them for several hours.

> While this is a semi-unrelated suggestion, perhaps history could be supplemented/replaced by small number indicators next to gags (showing 3 if you clicked on 3 hoses, for example.), just to add a extra level of user-friendliness, though this could be a painstaking process.

Luckily, performing painstaking processes is one of my hobbies, and this doesn't actually sound that awful. I can get started on this after live calculation is polished.

**Comment by Vhou-Atroph** [comment]
All gag tracks are enabled and *should* be working properly in livecalc-dev now.

**Comment by Vhou-Atroph** [comment]
Reliability has been tested in the flames of a three star field office, so I'd say live calculation is ready for main! livecalc-dev has been merged into main, and then removed.
