### ISSUE TITLE
[Enhancement] Gag Removal Functionality

### ISSUE THREAD

**Issue by supdogpsi** [Vhou-Atroph/TT-Damage-Calculator#6]
I want to say thanks and kudos for listening to my feedback - I think this is becoming a extremely useful cross-platform utility, especially since most gag calculators are either web based, TTO-only, or are made for Windows.

I have another suggestion to further increase time-efficiency - now that gags are quantified by numbers in the UI, it may be useful and expedient if a right click (or a alternate mode) could _remove_ a gag from the calculation - so the player can quickly undo mistakes or try different combinations without having to re-click every gag all over again via pressing "reset damage". This can be a bit annoying when brute-forcing combos, especially when you're strapped for time and communication. It'd also be fairly nice and intuitive compared to having to click the "reset damage" button all the time.

Example:
3 cakes selected (360 dmg)
Right-click cake icon
A cake is removed from the calculation, so it shows the result for 2 cakes (240 dmg)

The only real obstacle might be keeping track of organic calculations - but I am not versed in the code enough to know if this is a issue. I personally think right-clicking is the best way to handle this, as right-clicking currently has no functions, and many users may instinctually try right-clicking. (It's also faster then a dedicated mode, of course.)

**Comment by Vhou-Atroph** [comment]
Tkinter doesn't allow for buttons to have a right click command, but I will try to see if I can make it work.

**Comment by Vhou-Atroph** [comment]
Unfortunately I'm going to have to close this without a commit. Python either refuses to cooperate with me or this just isn't possible in a clean way.
